import 'bootstrap'
import './stylesheets/style.css'
import './stylesheets/popupS.css'
import './stylesheets/bootswatch.css'
import './javascript/jqueryService.js'
import './javascript/scannerService.js'
import './javascript/validationService.js'
import './javascript/ajaxService.js'
import './images/UC-logo.png'
import './images/logo.png'

